name: Deployment

on:
  push:
    branches:
      - TokeNew

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: deploy
        # ...deployment-specific steps
